### ISSUE TITLE
ant design 3.11.3 - Unhandled Rejection (Invariant Violation): Element type is invalid

### ISSUE THREAD

**Issue by Enalmada** [thangngoc89/bs-ant-design#25]
I am trying to upgrade ant design in my project and getting this error: `Unhandled Rejection (Invariant Violation): Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object`

I seem to have traced it to these lines: https://github.com/thangngoc89/bs-ant-design/blob/master/src/Antd_Layout.re#L20-L22

I found a reason-react page on this that gives some conditions I would get this error: https://reasonml.github.io/reason-react/docs/en/element-type-is-invalid 

Can someone try upgrading to latest antd and advise if there is any way to adjust the Antd_Layout bindings to work?

**Comment by thangngoc89** [comment]
I tried this recently and the issue is that the import statements aren't correct anymore (I mean all of them). The files were moved around.

**Comment by Enalmada** [comment]
Oh how frustrating.  Well if you can help me figure out what the fix would be for layout component Header for example I can help fix everything else up following that pattern.

**Comment by Enalmada** [comment]
The problem seems to be with the exports["default"]...the new antd typescript is no longer exporting children like Header of Layout.Header:

node_modules/antd/lib/layout/layout.js
```
Layout.Header = Header;
Layout.Footer = Footer;
Layout.Content = Content;
var _default = Layout;
exports["default"] = _default;
```

Here is what the current code is creating: 
```
  return ReasonReact.wrapJsForReason(Layout.Header, tmp, children);
```
If you change that `Layout.Header` manually to `Layout.default.Header` it works:
```
  return ReasonReact.wrapJsForReason(Layout.default.Header, tmp, children);
```

So how do we make the code add ".default" to the wrapJsForReason using bindings?

**Comment by dephora** [comment]
I'd be willing to contribute to whatever refactors need to be done to fix this.

**Comment by levic** [comment]
Looks like the issue is addressed in the docs and is due to the way babel exports ES6 module defaults: https://reasonml.github.io/reason-react/docs/en/element-type-is-invalid

So
```
[@bs.module]
external layout: ReasonReact.reactClass = "antd/lib/layout";
```

should read:
```
[@bs.module "antd/lib/layout"]
external layout: ReasonReact.reactClass = "default";
```

**Comment by levic** [comment]
This syntax appears to work for members of the default export:
```
module Header = {
  [@bs.module "antd/lib/layout"]
  external header: ReasonReact.reactClass = "Header";
```

should be

```
module Header = {
  [@bs.scope "default"] [@bs.module "antd/lib/layout"]
  external header: ReasonReact.reactClass = "Header";
```

**Comment by levic** [comment]
This seems to be exactly the same issue as #21 (so presumably same comments apply: if you don't generate es6 modules in your `bsconfig.json` then it might work without changes)

**Comment by waleedyt** [comment]
I am facing this same issue while using this package. I am newbee at Reason React and used the default setup from docs to set this up. I spent quite some time in figuring out and thought it was due to some syntax mistake i did. Once i stumbled on this post, i modified the file from my node_modules using approach levic mentioned above and it worked. 
As long as it's not fixed, perhaps you should add some pointer in Readme.md for newbees?

**Comment by waleedyt** [comment]
> Looks like the issue is addressed in the docs and is due to the way babel exports ES6 module defaults: https://reasonml.github.io/reason-react/docs/en/element-type-is-invalid
> 
> So
> 
> ```
> [@bs.module]
> external layout: ReasonReact.reactClass = "antd/lib/layout";
> ```
> 
> should read:
> 
> ```
> [@bs.module "antd/lib/layout"]
> external layout: ReasonReact.reactClass = "default";
> ```

@thangngoc89 if this is the fix that should be done, can i contribute and open a PR?

**Comment by OAGr** [comment]
This is quite frustrating. After a bit of tinkering, I finally noticed all the comments above (thanks @levic  and @aw-yt ) and wrote one version that I believe fixes this.
https://github.com/OAGr/bs-ant-design

I also couldn't tell if there was any easy way to test these, outside of importing them into a different repo. 

Happy to do a PR of that, though my setting may have changed the spacing a bit.

**Comment by Enalmada** [comment]
@OAGr  This fixed now?  Would you be in a position to do a pull request?

**Comment by Enalmada** [comment]
I believe this is fixed in https://github.com/Enalmada/bs-ant-design/pull/2 and will get merged in here eventually.

**Comment by OAGr** [comment]
Yea, his looks further along. At this point there are a bunch of forks that are pretty far along. I could submit a formal PR, but my guess is that my version would be more basic.
